### ISSUE TITLE
Percona Cluster SST scripts fail

### ISSUE THREAD

**Issue by shaneiseminger** [joyent/pkgsrc-joyent#13]
I don't know when Percona intends to fix this, and I don't know if you consider it something to patch in the Joyent package, but while setting up a Percona Cluster I ran into this bug:

https://bugs.launchpad.net/percona-xtradb-cluster/+bug/1263476

The fixes are quite simple. I was able to patch the sst_xtrabackup-v2 script and make it work with the given fix for the first bug (using lsof instead of ss) and I hardcoded the number of processors for the second bug. (I'm not entirely sure of the best solution to that.)

**Comment by mamash** [comment]
This was (finally) implemented on our end, earlier.
