### ISSUE TITLE
libsass needs patched libsass.pc.in with -R${libdir}

### ISSUE THREAD

**Issue by hypoalex** [joyent/pkgsrc-joyent#21]
pkgsrc/joyent/work/libsass-3.2.5/support/libsass.pc.in needs to be patched with:

Libs: -R${libdir} -L${libdir} -lsass

Without this, node modules using pkg-config to link will be unable to find libsass.so.0

Example failure: https://gist.github.com/hypoalex/faf374d802307918a62f
strace output: https://gist.github.com/hypoalex/7ccc09f80c4569fc2553

**Comment by mamash** [comment]
Thanks, I just fixed this program in pkgsrc trunk.
