### ISSUE TITLE
Python and DTrace support

### ISSUE THREAD

**Issue by xen0l** [joyent/pkgsrc-joyent#25]
Python 2.7 and Python 3.4 from pkgsrc should be patched to add full DTrace support. The patch is located here:
https://www.jcea.es/artic/python_dtrace.htm

This adds full support for tracing Python programs (w/ ustack helper support as well) and could be of benefit to Python users using SmartOS. The patch is maintained by the developer everyitme a new version of Python comes out.

**Comment by mamash** [comment]
Thanks, I'll contact the author, none of these currently build for me:

`
dtrace: failed to compile script ./Include/pydtrace.d: line 128: syntax error near "PyEval_EvalFrameEx"
`

**Comment by xen0l** [comment]
Which versions did you try? I might run myself and check it out. I was able to compile it on OpenIndiana.

**Comment by mamash** [comment]
Both 2.7 and 3.5 fail at the same thing. Trying to work the patches into the pkgsrc build of course, which is the only thing making sense.

**Comment by jperkin** [comment]
Close out old ticket, this was enabled a long time ago.
