### ISSUE TITLE
percona-xtrabackup is missing in 2016Q1 release

### ISSUE THREAD

**Issue by drscream** [joyent/pkgsrc-joyent#26]
The package `percona-xtrabackup` (name including the version: `percona56-xtrabackup`) is missing in pkgsrc 2016Q1 release for SmartOS zones. I also assume that `quickbackup-percona` requires `percona-xtrabackup` to work correctly but the dependency has been removed in the following commit: https://github.com/joyent/pkgsrc-joyent/commit/2bc5722e33877362b4c1a39da50093431a6d850d

It would be nice if someone could guide me to some information. If there is an alternative package which should be used for `quickbackup-percona` to resolve the dependency for commands like `innobackupex` which is used in that script.

**Comment by mamash** [comment]
It's actually more simple, as noted in the [duplicate issue](https://github.com/joyent/pkgsrc/issues/356#issuecomment-216247247). The xtrabackup package requires a specific version of boost, which we are past already in 2016Q1.

**Comment by mamash** [comment]
Now available in 2016Q1.
