### ISSUE TITLE
ClamAV is missing in 18.3.0

### ISSUE THREAD

**Issue by jcea** [joyent/pkgsrc-joyent#36]
In base-64 18.2.0:

```
# pkgin search clamav
...
clamav-doc-0.99.4    Anti-virus toolkit documents
clamav-0.99.4nb1     Anti-virus toolkit
```

In base-64 18.3.0:

```
# pkgin search clamav
clamav-doc-0.99.4    Anti-virus toolkit documents
```

**Result:**

ClamAV antivirus is missing.

**Expected result:**

ClamAV antivirus available.

Thanks!.

**Comment by jperkin** [comment]
Fixed in NetBSD/pkgsrc@1338b4f229efc3b15f89cc0384cb9fa3d50cec37, I'll try to get this back ported to 2018Q3.

**Comment by jcea** [comment]
Please, backport and let us know! Thanks a lot, Jonathan.

**Comment by jperkin** [comment]
This is now available.
