### ISSUE TITLE
"normalize" is missing in 18.3.0

### ISSUE THREAD

**Issue by jcea** [joyent/pkgsrc-joyent#37]
In base-64 18.2.0:

```
# pkgin search normalize
...
normalize-0.7.7nb7   Audio file volume normalizer (wav,mp3,ogg)
...
```

In base-64 18.3.0:

```
# pkgin search normalize
...
```

**Result:**

"normalize" utility is missing in 18.3.0.

**Expected Result:**

"normalize" utility available.

Thanks!

**Comment by jcea** [comment]
Maybe related or helpful: In other platforms, since "normalize" is a too broad name, the tool has been renamed to "normalize-audio".

**Comment by jperkin** [comment]
Fixed in NetBSD/pkgsrc@ce8ed724a09b9bbe11f1f256309f35cbe135b5a4, I'll try to get this back ported to 2018Q3.

**Comment by jcea** [comment]
Please, backport and let us know! Thanks a lot, Jonathan.

**Comment by jperkin** [comment]
This is now available.
